image: Ubuntu1804 # образ для сборки
stack: node 10 # окружение
branches:
  only:
    - master # ветка git
cache: node_modules # кеширование
install:
  - npm install --global yarn # команда установки зависимостей
build: off
build_script:
  - yarn build   # команда сборки
test_script:
  - yarn run lint && yarn test # скрипт сборки
